### ISSUE TITLE
bug: coverage always fails on pr from forked repo

### ISSUE THREAD

**Issue by varunsrin** [ScopeLift/foundry-template#15]
The coverage report fails only when opened by someone who has forked the repo and opened a PR, due to a failure in romeovs/lcov-reporter-action

See example here: https://github.com/farcasterxyz/contracts/actions/runs/4339987582/jobs/7578222499

Opening here since romeovs/lcov-reporter-action doesn't seem to be very active, in case you want to consider a different package that works for forks. 

```
Run romeovs/lcov-reporter-action@v0.3.1
RequestError [HttpError]: Resource not accessible by integration
    at /home/runner/work/_actions/romeovs/lcov-reporter-action/v0.3.1/dist/main.js:6018:23
    at processTicksAndRejections (internal/process/task_queues.js:97:5)
    at async main$1 (/home/runner/work/_actions/romeovs/lcov-reporter-action/v0.3.1/dist/main.js:23145:3) {
  status: 403,
  ```

**Comment by varunsrin** [comment]
See: https://github.com/romeovs/lcov-reporter-action/issues/6

**Comment by mds1** [comment]
Yea, pretty sure this is because it requires the `GITHUB_TOKEN` secret, which for security reasons is not provided to external contributors who open PRs. I'm not sure of a way to workaround this

**Comment by varunsrin** [comment]
yeah makes sense, without integrating with a third party service that you can approve there's probably no way to do this.
